version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: desafio-postgres

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: desafio-backend

    working_dir: /app
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8080:3333"
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://root:password@postgres:5432/desafio-db"

volumes:
  postgres_data:
