version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    container_name: desafio-back-end
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio-db
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
